# makefile.common

CXX = g++

# C++ flags

ARCH := $(shell getconf LONG_BIT)

CXX_FLAGS_32 := -m32
CXX_FLAGS_64 := -m64

CXXFLAGS := $(CXX_FLAGS_$(ARCH))
CXXFLAGS += -MD
CXXFLAGS += -Wall
CXXFLAGS += -Werror
CXXFLAGS += -O2
CXXFLAGS += -fopenmp
CXXFLAGS += -std=c++11
